services:
  db:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
       - "5431:80"
    depends_on:
      - db
  app:
     build: .
     ports:
       - "2803:2803"
     depends_on:
       - db
       - pgadmin
     env_file: .env
volumes:
  db_data:
