services:
  db:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: vm
      POSTGRES_PASSWORD: vm123456
      POSTGRES_DB: vm_db
    volumes:
      - db_data:/var/lib/postgresql/

  app:
    build: .
    ports:
      - "2803:2803"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vm_db
      SPRING_DATASOURCE_USERNAME: vm
      SPRING_DATASOURCE_PASSWORD: vm123456
volumes:
  db_data: