services:
  db:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/

  app:
    build: .
    ports:
      - "2803:2803"
    depends_on:
      - db
    env_file: .env
volumes:
  db_data:
