server:
  port: 2803
spring:
  application:
    name: api-rest-vm
  datasource:
    url: jdbc:postgresql://localhost:5430/vm_db
    username: vm
    password: vm123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
# JWT Configuration
jwt:
  secret: f8ab5529f4c892c0dfcefeed9d165bc0
  expirationTime: 3600000  # 1 hora em milissegundos