server:
  port: 2803
spring:
  application:
    name: api-rest-vm
  datasource:
    url: jdbc:postgresql://localhost:5430/vm_db
    username: vm
    password: vm123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
# JWT Configuration
jwt:
  secret: mySuperSecretKey
  expirationTime: 86400000  # 1 dia em milissegundos